create table TASK
(
    DOCUMENT_ID          BIGINT,
    DATE_OF_ISSUE        DATE,
    TERM_OF_EXECUTION    DATE,
    RESPONSIBLE_EXECUTOR BIGINT,
    SIGN_OF_CONTROL      VARCHAR(255),
    ORDER_CONTROLLER     BIGINT,
    FOREIGN KEY (RESPONSIBLE_EXECUTOR) REFERENCES PERSON (ID),
    FOREIGN KEY (ORDER_CONTROLLER) REFERENCES PERSON (ID),
    FOREIGN KEY (DOCUMENT_ID) REFERENCES DOCUMENT (ID)
        ON DELETE SET NULL
)