create table OUTGOING
(
    DOCUMENT_ID     BIGINT,
    ADDRESSEE       VARCHAR(255),
    DELIVERY_METHOD VARCHAR(255),
    FOREIGN KEY (DOCUMENT_ID) REFERENCES DOCUMENT (ID)
        ON DELETE SET NULL
)