create table INCOMING
(
    DOCUMENT_ID                BIGINT,
    SOURCE                     BIGINT,
    ADDRESSEE                  VARCHAR(255),
    OUTGOING_NUMBER            BIGINT,
    OUTGOING_REGISTRATION_DATE DATE,
    FOREIGN KEY (SOURCE) REFERENCES PERSON (ID)
        ON DELETE SET NULL,
    FOREIGN KEY (DOCUMENT_ID) REFERENCES DOCUMENT (ID)
        ON DELETE SET NULL
)